### ISSUE TITLE
Problem with getting version name from apk due to wrong regex

### ISSUE THREAD

**Issue by hoboris** [transcovo/fastlane-plugin-s3-android#7]
In `fastlane-plugin-s3-android/lib/fastlane/plugin/s3_android/actions/s3_android.rb`
`get_version_cmd = aapt_binary + " dump badging " + path_to_apk` is returning 
`package: name='com.example.myapp' versionCode='100001' versionName='1.0.0'`
But the regex `get_version.scan(/versionName='(.*)\.(.*)\.(.*)' /).first.join(".")` is expecting 
`package: name='com.example.myapp' versionCode='100001' versionName='1.0.0' ` (with an extra space after the version name)
As the string can't be matched we get an `undefined method 'join' for nil`

**Comment by jerome-gr** [comment]
Hi @hoboris, 
Thanks for your feedback
Feel free to submit a pull request to correct this issue :-)
